{% set xorg_name = "libXScrnSaver" %}
{% set name = "xorg-" ~ xorg_name %}
{% set version = "1.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://www.x.org/releases/individual/lib/{{ xorg_name }}-{{ version }}.tar.xz
  sha256: 75cd2859f38e207a090cac980d76bc71e9da99d48d09703584e00585abc920fe

build:
  number: 0
  # xorg-libxdmcp, libxcb, libx11 aren't available on Windows because their dependencies clash with m2/msys2 and mingw64/ucrt64 toolchains.
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name|lower) }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler("c") }}
    - pkg-config
    - gnuconfig
    - make
  host:
    - xorg-xorgproto
    - xorg-libx11
    - xorg-libxext
    - xorg-util-macros

test:
  commands:
    {% set lib_idents = [ "Xss" ] %}
    {% for lib_ident in lib_idents %}
    - test -f $PREFIX/lib/lib{{ lib_ident }}.dylib  # [osx]
    - test -f $PREFIX/lib/lib{{ lib_ident }}.so  # [linux]
    {% endfor %}

about:
  home: https://www.x.org/
  dev_url: https://gitlab.freedesktop.org/xorg/lib/libxscrnsaver
  doc_url: https://gitlab.freedesktop.org/xorg/lib/libxscrnsaver
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: The X.org X11 Xlib-based X11 Screen Saver extension client library
  description: The X.org X11 Xlib-based X11 Screen Saver extension client library

extra:
  recipe-maintainers:
    - zklaus
